---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.6.1
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-data  
              mountPath: /data

      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3
          command:
          - chown
          - -R
          - 10001:10001
          - /data
          volumeMounts:
            - name: loki-data
              mountPath: /data
        
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data  
          persistentVolumeClaim:
            claimName: loki-pvc
        

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitor
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100