---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: sample
  labels:
    fargate: "yes"
    app.kubernetes.io/name: sample
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/version: latest
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |-
    [SERVICE]
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_PORT      2020
        Flush          1
        Daemon         Off
        Log_Level      warn
        Parsers_File   parsers.conf
    [INPUT]
        Name              tail
        Tag               *
        Path              /app/logs/*.log
        Parser            docker
        DB                /app/logs/flb_kube.db
        Mem_Buf_Limit     5MB
        Buffer_Chunk_size 32k
        Buffer_Max_size   32k  
    [Output]
        Name grafana-loki
        Match *
        Url http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
        TenantID ""
        BatchWait 1
        BatchSize 1048576
        Labels {service="wp-be"}
        RemoveKeys kubernetes,stream
        AutoKubernetesLabels true
        # LabelMapPath /fluent-bit/etc/labelmap.json
        LineFormat json
        LogLevel warn
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    fargate: "yes"
    app.kubernetes.io/name: sample
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/version: latest
  name: sample
  namespace: sample
---
apiVersion: v1
kind: Service
metadata:
  labels:
    fargate: "yes"
    app.kubernetes.io/name: sample
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/version: latest
  name: sample
  namespace: sample
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    fargate: "yes"
    app.kubernetes.io/name: sample
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/version: latest
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample
  labels:
    fargate: "yes"
  namespace: sample
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: sample
    namespace: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: sample
  labels:
    fargate: "yes"
    app.kubernetes.io/name: sample
    app.kubernetes.io/part-of: sample
    app.kubernetes.io/version: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      fargate: "yes"
      app.kubernetes.io/name: sample
      app.kubernetes.io/part-of: sample
      app.kubernetes.io/version: latest
  template:
    metadata:
      labels:
        fargate: "yes"
        app.kubernetes.io/name: sample
        app.kubernetes.io/part-of: sample
        app.kubernetes.io/version: latest
      namespace: sample
    spec:
      containers:
        - name: wp-be-container
          image: sample-image
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: wp-be-app-configs
            - secretRef:
                name: wp-be-secrets
          volumeMounts:
            - name: log-volume
              mountPath: app/logs
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 150
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /  
              port: 3000       
            initialDelaySeconds: 150  # Delay before first probe is initiated
            periodSeconds: 10 # How often to perform the probe
            successThreshold: 1
        - name: fluentbit-wp
          image: grafana/fluent-bit-plugin-loki:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 2020
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /fluent-bit/etc/
            - name: log-volume
              mountPath: app/logs
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluent-bit-config-wb
      serviceAccountName: sample
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0