---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: loki
type: Opaque
data:
  admin-user: YWRtaW4= 
  admin-password: YWRtaW4= 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: loki
spec:
  serviceName: grafana-svc
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
     name: grafana
     labels:
      app: grafana
    spec:
      containers:  
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana-secrets
                key: admin-user
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-secrets
                key: admin-password
          - name: GF_INSTALL_PLUGINS
            value: ""        
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
          subPath: grafana 
        readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
        livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1               
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        # Give `grafana` user (id 472) permissions a mounted volume
        # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
        command:
        - chown
        - -R
        - 472:472
        - /var/lib/grafana
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
          subPath: grafana            
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-qa-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: loki
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

